### ISSUE TITLE
Rewrite of Solid Core Docs

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/solid-docs#267]
<h2>The Problem</h2>
Solid's core docs are in desperate need of a rewrite. At the moment, our documentation does not maximize its potential for clarity and ease of use. Information is scattered and can be difficult to locate, leading to confusion for anyone working in the docs. Additionally, there is a lot of inconsistent structure and formatting, as well as grammar since there are no style rules applied.

<h2>Scope</h2>

This issue is intended to track the progress of the Core docs rewrite. A new issue will be opened in the future for the API Reference section.

The primary goal for this is consistency and clarity. Our wonderful contributors have done a great job with keeping information up to date, but there are gaps that need to be addressed. For example, most of the information is already present in the docs, they just need to better organized and structured to make it easier to navigate. At the moment, Solid has a lot of complicated concepts that tend to be only briefly touched upon. This makes it difficult for beginners to take up and troubleshooting is another hurdle.

In another issue, we will be addressing the style/writing guide to talk about the grammar, styling, and any other information that contributors will need to know if they are looking to add a new page to the docs.

Each page will end up below will have its own issue - in these, we will be elaborate more on the content of the page.

The goal is to be finished sometime around the end of August. This issue is intended to be used as a way to keep track of the progress.

- Contributor Info
     - [x] Contribution Guide - #279 
     - [x] Writing Guide - #268

- Introduction
     - [x]  Overview - #269 
     - [x] Quick Start Tutorial - #273 

- Essentials
     - [x]  Understanding JSX Syntax - #275
     - [x] Introduction to Reactivity - #317 
     - [x] Components & Props - #276
     - [x] Class & Style Bindings - #277 
     - [x] Signals - #278
     - [x] Effects - #332
     - [x] Memos - #333 
     - [x] Stores - #352 
     - [x] Control Flow - #343 
     - [x] List Rendering - #343 
     - [x] Event Handling - #277 
     - [x] Refs - #277
     - [x] Context
- Tutorials
     - [x]  Beginner Tutorial
- Guides
    - [x]  Styling your Components - #324
    - [x] Routing & Navigation - #344
    - [x] Fetching Data - #354
    - [x] State Management - #349 
    - [x] Deploying your App - #331
    - [x] TypeScript for Solid - #310
    - [ ] Testing  (postponed for site remodel)
- Advanced
    - [x] Understanding fine-grained reactivity - #347 
- Additional Resources
     - [x] Contribution Guide
